// radioactive isotopes
const isotopes = [
  { elem: "H", atomicNumber: 1, isotope: "3", decays: "beta-" },
  { elem: "He", atomicNumber: 2, isotope: "6", decays: "beta-" },
  { elem: "He", atomicNumber: 2, isotope: "8", decays: "beta-" },
  { elem: "Li", atomicNumber: 3, isotope: "8", decays: "beta-" },
  { elem: "Li", atomicNumber: 3, isotope: "9", decays: "beta-" },
  { elem: "Li", atomicNumber: 3, isotope: "11", decays: "beta-" },
  { elem: "Be", atomicNumber: 4, isotope: "7", decays: "electron capture" },
  { elem: "Be", atomicNumber: 4, isotope: "10", decays: "beta-" },
  { elem: "B", atomicNumber: 5, isotope: "8", decays: "beta+, alpha" },
  { elem: "B", atomicNumber: 5, isotope: "12", decays: "beta-" },
  { elem: "B", atomicNumber: 5, isotope: "14", decays: "beta-" },
  { elem: "C", atomicNumber: 6, isotope: "11", decays: "beta+" },
  { elem: "C", atomicNumber: 6, isotope: "14", decays: "beta-" },
  { elem: "N", atomicNumber: 7, isotope: "13", decays: "beta+" },
  { elem: "N", atomicNumber: 7, isotope: "16", decays: "beta-" },
  { elem: "O", atomicNumber: 8, isotope: "15", decays: "beta+" },
  { elem: "O", atomicNumber: 8, isotope: "19", decays: "beta-" },
  { elem: "F", atomicNumber: 9, isotope: "18", decays: "beta+" },
  { elem: "F", atomicNumber: 9, isotope: "20", decays: "beta-" },
  { elem: "Ne", atomicNumber: 10, isotope: "19", decays: "beta+" },
  { elem: "Ne", atomicNumber: 10, isotope: "23", decays: "beta-" },
  { elem: "Na", atomicNumber: 11, isotope: "22", decays: "beta+" },
  { elem: "Na", atomicNumber: 11, isotope: "24", decays: "beta-" },
  { elem: "Mg", atomicNumber: 12, isotope: "28", decays: "beta-" },
  { elem: "Al", atomicNumber: 13, isotope: "26", decays: "beta+, electron capture" },
  { elem: "Al", atomicNumber: 13, isotope: "29", decays: "beta-" },
  { elem: "Si", atomicNumber: 14, isotope: "31", decays: "beta-" },
  { elem: "P", atomicNumber: 15, isotope: "32", decays: "beta-" },
  { elem: "P", atomicNumber: 15, isotope: "33", decays: "beta-" },
  { elem: "S", atomicNumber: 16, isotope: "35", decays: "beta-" },
  { elem: "Cl", atomicNumber: 17, isotope: "36", decays: "beta-, electron capture" },
  { elem: "Ar", atomicNumber: 18, isotope: "39", decays: "beta-" },
  { elem: "Ar", atomicNumber: 18, isotope: "42", decays: "beta-" },
  { elem: "K", atomicNumber: 19, isotope: "40", decays: "beta-, electron capture" },
  { elem: "K", atomicNumber: 19, isotope: "42", decays: "beta-" },
  { elem: "K", atomicNumber: 19, isotope: "43", decays: "beta-" },
  { elem: "Ca", atomicNumber: 20, isotope: "45", decays: "beta-" },
  { elem: "Ca", atomicNumber: 20, isotope: "47", decays: "beta-" },
];
